# Question-1

You are given a space separated list of numbers.
Your task is to print a reversed NumPy array with the element type float.

Input Format

A single line of input containing space separated numbers.

Output Format

Print the reverse NumPy array with type float.

In [2]:
import numpy

def arrays(arr):
    a = numpy.array(arr, dtype = float)
    b = numpy.array(arr[::-1], dtype = float)
    return b

arr = input().strip().split(' ')
result = arrays(arr)
print(result)

1 2 3 4 -8 -10
[-10.  -8.   4.   3.   2.   1.]


# Question-2

You are given a space separated list of nine integers. Your task is to convert this list into a 3X3 NumPy array.

Input Format

A single line of input containing 9 space separated integers.

Output Format

Print the 3X3 NumPy array.

In [3]:
import numpy

l = numpy.array(input().split(' '), int)
print (l.reshape(3, 3))

1 2 3 4 5 6 7 8 9
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Question-3
You are given a N*M integer array matrix with space separated elements ( N = rows and M = columns).
Your task is to print the transpose and flatten results. 


Input Format :
The first line contains the space separated values of N and M.
The next N lines contains the space separated elements of M columns.
 
Output Format :
First, print the transpose array and then print the flatten.

In [4]:
import numpy
n, m = map(int, input().split())
array = numpy.array([input().strip().split() for i in range(n)], int)
print (array.transpose())
print (array.flatten())

2 2
1 2
3 4
[[1 3]
 [2 4]]
[1 2 3 4]


# Question-4
You are given two integer arrays of size N X P and M X P (N & M are rows, and P is the column). Your task is to concatenate the arrays along axis 0.

Input Format

The first line contains space separated integers N, M and P. The next N lines contains the space separated elements of the P columns. After that, the next M lines contains the space separated elements of the P columns.

Output Format

Print the concatenated array of size (N+M)XP.

In [6]:
import numpy

n,m,p=map(int,input().split())

l1=[list(map(int,input().split())) for i in range(n)]
l2=[list(map(int,input().split())) for i in range(m)]
a1=numpy.array(l1)
a2=numpy.array(l2)

print(numpy.concatenate((a1,a2),axis=0))

4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


# Question-5
You are given the shape of the array in the form of space-separated integers, each integer representing the size of different dimensions, your task is to print an array of the given shape and integer type using the tools numpy.zeros and numpy.ones.

Input Format

A single line containing the space-separated integers.

Output Format

First, print the array using the numpy.zeros tool and then print the array with the numpy.ones tool.

In [8]:
import numpy

k = tuple(map(int,input().strip().split()))
print(numpy.zeros(k, int))
print(numpy.ones(k, int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


# Question-6
Your task is to print an array of size X with its main diagonal elements as 1's and 0's everywhere else.

Input Format

N denotes rows M demotes coloumns

Output Format

Print the desired N X M array.

In [12]:
import numpy
numpy.set_printoptions(sign=' ')

N, M = map(int, input().split())
eye = numpy.eye(N, M)
print(eye)

3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


# Question-7
You are given two integer arrays, and of dimensions X.

Your task is to perform the following operations:

Add ( + ) Subtract ( - ) Multiply ( * ) Integer Division ( / ) Mod ( % ) Power ( ** )

Input Format

The first line contains two space separated integers, and . The next lines contains space separated integers of array . The following lines contains space separated integers of array .

Output Format

Print the result of each operation in the given order under Task.

In [13]:
import numpy
n,m = map(int,input().split())
a = numpy.array([input().split() for _ in range(n)],int)
b = numpy.array([input().split() for _ in range(n)],int)
print(a+b,a-b,a*b,a//b,a%b,a**b,sep="\n")

1 4
1 2 3 4
5 6 7 8
[[ 6  8 10 12]]
[[-4 -4 -4 -4]]
[[ 5 12 21 32]]
[[0 0 0 0]]
[[1 2 3 4]]
[[    1    64  2187 65536]]


# Question-8
Task 5 : Floor, Ceil and Rint
Input Format

A single line of input containing the space separated elements of array .

Output Format

On the first line, print the of A. On the second line, print the of A. On the third line, print the of A.

In [15]:
import numpy

numpy.set_printoptions(sign=' ')

array = numpy.array(input().split(),float)

print(numpy.floor(array))
print(numpy.ceil(array))
print(numpy.rint(array))

1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


# Question-9
You are given a 2-D array with dimensions X. Your task is to perform the tool over axis and then find the of that result.

Input Format

The first line of input contains space separated values of and . The next lines contains space separated integers.

Output Format

Compute the sum along axis . Then, print the product of that sum.

In [21]:
import numpy

N, M = map(int, input().split())

array = numpy.array([input().split() for i in range(N)], int)

print(numpy.prod(numpy.sum(array, axis = 0), axis = None))

2 2
1 2
3 4
24


# Question-10
Task 15 : Min and Max

You are given a 2-D array with dimensions N X M. Your task is to perform the min function over axis 1 and then find the max of that.

Input Format

The first line of input contains the space separated values of N and M . The next N lines contains M space separated integers.

Output Format

Compute the min along axis 1 and then print the max of that result.

In [22]:
import numpy
N, M = map(int, input().split())

A = numpy.array([input().split() for i in range(N)],dtype = int)
print(numpy.max(numpy.min(A, axis=1), axis=0))

4 2
2 5
3 7
1 3
4 0
3


# Question-11
You are given a 2-D array of size X. Your task is to find:

The mean along axis 1

The var along axis 0

The std along axis none

Input Format

The first line contains the space separated values of and . The next lines contains space separated integers.

Output Format

First, print the mean. Second, print the var. Third, print the std.

In [23]:
import numpy
numpy.set_printoptions(legacy='1.13')

N, M = map(int, input().split())
A = numpy.array([input().split() for i in range(N)], dtype =int)
print(numpy.mean(A, axis =1))
print(numpy.var(A, axis =0))
print(numpy.std(A, axis = None))

2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


# Question-12
Task 12 : Dot and Cross
    
You are given two arrays A and B. Both have dimensions of NXN.

Your task is to compute their matrix product.

Input Format

The first line contains the integer N. The next lines N contains N space separated integers of array A . The following N lines contains N space separated integers of array B .

Output Format

Print the matrix multiplication of A and B.

In [25]:
import numpy
N = int(input())
A = numpy.array([input().split() for i in range(N)], dtype =int)
B = numpy.array([input().split() for i in range(N)], dtype =int)
C = numpy.dot(A,B)
print(C)

2
1 2
3 4
1 2
3 4
[[ 7 10]
 [15 22]]


# Question-13
Task 10 : Inner and Outer
    
You are given two arrays:  A and B. 

Your task is to compute their inner and outer product.

Input Format

The first line contains the space separated elements of array A. 

The second line contains the space separated elements of array B.

Output Format

First, print the inner product. Second, print the outer product.

In [26]:
import numpy

A = numpy.array(input().split(), int)
B = numpy.array(input().split(), int)

print (numpy.inner(A, B))
print (numpy.outer(A, B))

0 1
2 3
---------------------------
3
---------------------------
[[0 0]
 [2 3]]


# Question-14
You are given the coefficients of a polynomial P. Your task is to find the value of P at point x.

Input Format

The first line contains the space separated value of the coefficients in P. The second line contains the value of x.

Output Format

Print the desired value.

In [27]:
import numpy
m = numpy.array(input().split(), float)
n = float(input())
print(numpy.polyval(m, n))

1.1 2 3
0
3.0


# Question-15
You are given a square matrix with A dimensions NXN. Your task is to find the determinant.

Input Format

The first line contains the integer N.

The next N lines contains the N space separated elements of array A .

Output Format

Print the determinant of .

In [28]:
import numpy

numpy.set_printoptions(legacy='1.13')

N = int(input())

A = numpy.array([input().split() for i in range(N)], float)
print(numpy.linalg.det(A))

2
1.1 1.1
1.1 1.1
0.0
